karma.conf.js
package-lock.json
package.json
src/test/text-fragment-utils-test.js

This adds test support using Karma and Jasmine. Tests can be added to the `src/test` directory and run with `npm test`. So far, this only includes an extremely basic test to demonstrate that everything works end-to-end.

Adding Karma + Jasmine test support

---

karma.conf.js
src/test/basic_test.expected.html
src/test/basic_test.html
src/test/text-fragment-utils-test.js

This adds a simple HTML test of the marking logic in its most basic case (a straightforward text match inside a <p> tag). It should be useful as a model for writing additional HTML tests.

Adding simple HTML test

---

README.md
demo/index.html
src/text-fragments.js

- Exclusively support the new location in the polyfill itself.
- Support the legacy location in the demo and the usage notes. Eventually, these can be removed, too (opened a [reminder issue](https://github.com/GoogleChromeLabs/text-fragments-polyfill/issues/9) to keep this on the radar).

Reflect `fragmentDirective` location change

---

src/text-fragment-utils.js

This commit adds a line needed for the module to be imported into closure-compiled projects (i.e., allows importing the module using `goog.require()`). 
It also exports one additional function which was previously hidden.

Adding closure compatibility

---

src/test/boundary-points.html
src/test/text-fragment-utils-test.js
src/text-fragment-utils.js

This pull will add two needed utils: one which normalizes a string for comparisons, and one which helps us find the boundary points of a Range in the _real DOM_ based on an index in the _normalized_ text.

Add boundary point and string normalization utils

---

package-lock.json
package.json
src/text-fragment-utils.js
src/text-fragments.js
tools/generate-boundary-regex.js

For consistency, this changes the install scripts to use clang-format and Google JS style, rather than Prettier style. It also updates the affected source files to apply the new formatting.

Changing tooling to use Google Style

---

src/test/ambiguous-match.html
src/test/text-fragment-utils-test.js
src/text-fragment-utils.js

This patch restructures the logic for finding matches which
include a suffix. Specifically, the existing logic does not loop,
meaning that if the first found textStart or textEnd doesn't
occur immediately before a suffix, we assume no suffix exists.

Improve robustness of suffix matching

---

src/text-fragment-utils.js

Closure compilation was broken by the switch to clang-format. This corrects the issue.

Fix closure compile

---

package.json

This bumps the version to 1.0.0. Work on parsing, finding, and highlighting text fragments is now complete (though future versions will include improvements and bug fixes).

Bump to v1.0.0

---

package-lock.json
package.json
src/fragment-generation-utils.js
src/text-fragment-utils.js
test/fragment-generation-utils-test.js
test/text-fragment-utils-test.js

This patch:
* Defines the high-level interface for fragment generation, with a stub that should allow us to start testing integrations
* Adds a new file which will contain this logic moving forward
* Bumps the version to 1.1 to reflect the new (in-development) functionality
* Adds test files to automatic formatting

Stubbing out generation

---

package-lock.json
src/fragment-generation-utils.js
src/text-fragment-utils.js
test/fragment-generation-utils-test.js
test/word_bounds_test.html

This patch makes the fragment generation process respect word and
block boundaries by expanding the start of the user selection (if
necessary).
End boundaries will follow similar logic but the logic was already
pretty complex just for one side, so I will tackle that in a follow-up.

Expanding selection during fragment generation to word start

---

src/fragment-generation-utils.js
test/fragment-generation-utils-test.js

This is the first step towards range (textStart + textEnd) matching: checking whether or not it's needed in the first place :)
The bulk of the logic here is just to check if a given range contains a block boundary (so that we can identify cases where an exact match is not possible). One test is currently disabled because of a known issue with forward traversal.

Adding checks for range matching

---

src/fragment-generation-utils.js
test/fragment-generation-utils-test.js
test/postorder-tree.html

Currently when trying to find block boundaries in the forward
direction, we use a postorder traversal so that the ends of blocks
can be found. However, this only makes sense if the traversal
started inside those nodes--otherwise, we'd want to hit the
leading edge. This change adopts a new approach based on
"injecting" these ancestor nodes into the traversal order using an
override map. This solves the known bugs (the disabled test).

Using override map approach for traversal

---

package-lock.json
package.json
src/text-fragment-utils.js
test/text-fragment-utils-test.js

This CL updates the logic in `processTextFragmentDirective` to find
*all* ranges matching the target text, not just the first.
Notably, this means `processTextFragmentDirective` returns a list of
ranges, not a list of `mark` nodes, so users that access that method
directly will need to make client changes. Accordingly, the
version number is bumped to `2.0.0-alpha`

Find ambiguous matches when processing fragments

---

src/fragment-generation-utils.js
test/fragment-generation-utils-test.js
test/postorder-tree.html

This adds a `backwardTraverse` which serves a similar purpose to the existing `forwardTraverse`, though the implementation is quite different. It will make existing block detection (for when we need to expand the range) more accurate in edge cases, and will be needed for the next patch, which generates the search space for range matching.

Implementing backwardTraverse

---

src/fragment-generation-utils.js
test/fragment-generation-utils-test.js
test/range-fragment-test.html

This patch implements fragment generation for ranges that cross a block boundary. It also includes a few bugfixes and reorganization that came up in the process of testing the new generation logic.
A follow-up patch will implement textStart/textEnd-based fragments for ranges that *don't* cross a block boundary (e.g., 1000 characters all selected from the same paragraph).

Generate fragments that cross block boundaries

---

package.json
src/fragment-generation-utils.js
test/fragment-generation-utils-test.js
test/very-long-text.html

This patch adds support for range matching within a block, which can be invoked for very long text selections (300+ char) that don't cross block boundaries.
Since this completes the range matching functionality (except bug fixes, tech debt, etc.), this also includes a version bump to 2.0.0.

Adding support for range matches in block

---

src/text-fragment-utils.js
test/text-fragment-utils-test.js

This allows scrolling to fragments which have boundary characters at the beginning or end of the fragment.

Fixed boundary chars at fragment's ends

---

src/fragment-generation-utils.js

The return {status: GenerateFragmentStatus.INVALID_SELECTION}; could never be reached.

Remove unreachable return statement

---

package-lock.json
src/fragment-generation-utils.js
src/text-fragment-utils.js
test/fragment-generation-utils-test.js

This patch slightly refactors range-based matching, achieving two
things:
* Making it slightly more robust (see the diff in the test to see
the affected case)
* Collecting the state that will determine if/when to use context
in a subsequent patch

Refactoring range matching to prepare for context

---

src/fragment-generation-utils.js
test/fragment-generation-utils-test.js

This adds the first chunk of the context (prefix/suffix) match generation logic to the FragmentFactory.
This is not currently on the critical path; only in test. A follow-up patch will actually *generate* the search space, and pass it to the factory. The factory constructor will get reworked a bit at that time, but I didn't want this to be a breaking change for the current critical path, so the current (temp) implementation is just optional setters.

Adding context logic to FragmentFactory

---

src/fragment-generation-utils.js
test/fragment-generation-utils-test.js

This patch adds the concept of modes to FragmentFactory, which
correspond to three new initialization methods which replace the
data formerly passed in at construct-time.
This is the last set-up step before adding context-based matches;
all that remains after this is to generate the search spaces and
pass them in.

Reorganizing FragmentFactory initialization

---

src/text-fragment-utils.js
test/text-fragment-utils-test.js

Currently, we search for *every* location in the document matching
the fragment; this, in turn, is making URL generation timeout in
Chrome. We only really need to find 2 instances to know that a
fragment is ambiguous, so this patch halts the search after 2 are
found.

Optimize ambiguous match checking

---

src/text-fragment-utils.js
test/fragment-generation-utils-test.js
test/table.html
test/text-fragment-utils-test.js

This patch adds table-related elements (tr, td, etc.) as block
elements, which seems to improve reliability and robustness in
real-world usage.

Improve table support

---

src/text-fragment-utils.js
test/target-text-test.html
test/text-fragment-utils-test.js

Lookup ::target-text background-color
This PR allow the lookup of the pseudo element `::target-text` background color responsible for styling the Text Fragment.

Support ::target-text background-color lookup

---

src/text-fragment-utils.js
src/text-fragments.js
test/target-text-test.html
test/text-fragment-utils-test.js

Update text-fragments
This PR changes the default background color of the text fragment to a light purple, which can only be overridden by `::target-text`.

Update text-fragments to reflect style changes

---

src/text-fragment-utils.js
test/default_style.html
test/target-text-test.html
test/text-fragment-utils-test.js

This PR adds a method that will add a default text-fragments-polyfill-target-text class at the top of the style sheet.

Add default class

---

package-lock.json
package.json
src/fragment-generation-utils.js
test/fragment-generation-utils-test.js

This patch adds a 400ms max run time to fragment generation, to
mitigate performance issues that can occur when runtime is excessive.
Bumps version to 3.0.0 since users who care about the |status| field
of GenerateFragmentResult need to handle a new enum value, but this
is not a widely breaking change.

Add timeout to fragment generation

---

src/text-fragment-utils.js
test/text-fragment-utils-test.js

This PR applies the `::target-text` pseudo element style before appending the text fragment default style.

Apply target-text style before setting text fragment default class

---

package.json
src/fragment-generation-utils.js
test/fragment-generation-utils-test.js

Rather than letting the timeout error escape the public API, we'll
catch it and return a new GenerateFragmentStatus code. This is in
response to feedback that having both status codes and errors led
to messier integrations.
This patch also includes a bit of housekeeping:
* Private methods are moved down below all public ones
* A few missing JSDocs are added

Update timeout API to use new status code

---

src/text-fragments.js

The current init logic first checks whether `document.readyState === 'complete'` before calling `init()`, otherwise it starts listening for the `DOMContentLoaded` event and sets `init()` as the event callback.
According to the [DOMContentLoaded](https://developer.mozilla.org/en-US/docs/Web/API/Document/DOMContentLoaded_event) documentation, it can fire while `document.readyState` is still `'interactive'`. So, the current logic has a race condition where if the `DOMContentLoaded` event has already fired before we can start listening to it, and the `document.readyState` isn't `'complete'` yet, then `init()` will never be called. This was preventing the polyfill from working for the demo page (and other simple pages on the web like [www.example.com](www.example.com)) in some cases, such as …

Fix race condition during initialization

---

src/fragment-generation-utils.js
test/fragment-generation-utils-test.js
test/non-word-boundaries.html

The getSearchSpaceForStart function currently does not return if it hits a block boundary but the trimmed search space is an empty string. This causes the traversal to continue, which doesn't make sense because the search space cannot cross block boundaries.
The fix is to return undefined, because it has been determined that there are no more words after the selection within the block, meaning there is no additional search space.
Fixes #63

searchSpace: add return if trimmed search space is empty

---

src/fragment-generation-utils.js
test/fragment-generation-utils-test.js
test/non-word-boundaries.html

The current |createForwardOverrideMap| function can create cycles, which could potentially lead to infinite loops when traversing the DOM under certain circumstances.
The problem is that when creating an override, |walker.nextNode()| is used to determine which node to traverse next. This is wrong if the node to be traversed next had already been overridden. The fix is to simply check the override map to see if the current node already had an override for its next node, and if so, use that as the ancestor's override.
Fixes #61

Fix overrideMap generation logic

---

src/fragment-generation-utils.js

The recent fix of returning early when determining the search space has broken a range-based generation unit test. It is safer to undo the change, especially since the cycle generation in the override map has been fixed, which is sufficient to address the generation failures and to pass the corresponding unit tests.
Fixes #67

Undo the early return in getSearchSpaceForStart

---

test/text-fragment-utils-test.js

The expectations on 2 unit tests were wrong because of quirks related to HTML formatting. This fix should bring back all tests to green status.

Fix test expectations causing failures

---

src/text-fragment-utils.js
test/ambiguous-match-2.html
test/text-fragment-utils-test.js

The current implementation of range matching ignores punctuation between the prefix and the text start. Not only is this not up to specs, it can cause false positives in range matches.
The problem is that when looking for the text start, the algorithm advances to the first non-boundary position after matching the prefix. According to the specs it should instead advance to the first non-whitespace position.
Because the |advanceRangeStartToNonBoundary| function was only used for range matching, it was repurposed for this fix rather than creating a new function.
Fixes #70

Fix range matching when punctuation is involved

---

src/fragment-generation-utils.js
test/fragment-generation-utils-test.js

Replaces the use of the custom function `trimBoundary()` when determining search spaces for prefixes, suffixes, text starts and text ends with the use of the built-in function `String.trim()`.
Because the range matching specs stipulate that the text start should start at the first non-whitespace character following the prefix, not including punctuation between the prefix and the text start within the prefix would result in unmatched fragments.
Fixes #66

Include punctuation in prefixes/suffices/selection

---

src/fragment-generation-utils.js
test/fragment-generation-utils-test.js

With #73, the trimBoundary() function isn't needed anymore, so this CL removes it. If we ever need it back, we can add it from history.

Clean up trimBoundary util

---

src/fragment-generation-utils.js
test/fragment-generation-utils-test.js
test/prefix-suffix-at-edges.html

Previously we would not attempt to add a prefix/suffix unless both
prefix and suffix had a nonempty search space, which means that,
for example, we couldn't generate a link to either instance of
"target" in the paragraph:
target suffix prefix target
This patch attempts to add a prefix/suffix if either one has a
nonempty search space.

Fix prefix/suffix issue

---

package-lock.json
package.json
src/text-fragment-utils.js
test/text-fragment-utils-test.js

This patch allows the optional use of Intl.Segmenter for improved word bound checks. Note that this does not, by default, affect the end-to-end fragment finding algorithm. A future patch will actually *supply* a Segmenter (where available) so that this logic will be applied.

Use Intl.Segmenter in word bound check

---

package-lock.json
package.json
src/text-fragment-utils.js
test/text-fragment-utils-test.js

This change supplies an Intl.Segmenter instance to the word bound
checking utils, where supported. This dramatically improves
the chances of a successful highlight in Japanese, Chinese, and
other non-space-separated languages.
This is not a breaking change. The old logic still exists and
is used in browsers which do not yet support Intl.Segmenter, and
the modified util functions treat the segmenter as an optional arg.
However, because this significantly affects real-world behavior, I
am treating this as a major version upgrade (4.0).

Use Intl.Segmenter for highlighting, where available

---

package.json
src/fragment-generation-utils.js
test/fragment-generation-utils-test.js
test/jp-word-boundary.html

This change updates the expandRangeStartToWordBound method to use
Intl.Segmenter, where supported. A follow-up patch will modify the
corresponding range end method, using similar logic.

Update range expansion algorithm to use Intl.Segmenter

---

package-lock.json
src/fragment-generation-utils.js
test/fragment-generation-utils-test.js

This patch mirrors the last, which implemented Intl.Segmenter support for expanding range starts.
Specifically, it:
* Extracts most of the logic of `expandRangeStartToWordBound` to a new helper method, `expandToNearestWordBoundaryPointUsingSegments`.
* Adds logic to `getTextNodesInSameBlock` to also return any text subnodes of the given node, if it is not already a text node. This is mainly needed because DOM traversal works differently in reverse (if we traverse _forward_ from `node` we will traverse all of its children; if we traverse _backward_ from `node` we do not).
The diff will also show some changes to `backwardTraverse` and the existing body of `expandRangeStartToWordBound`, but these are just auto-formatting.

Use Intl.Segmenter for expanding range ends to word bounds

---

src/fragment-generation-utils.js
test/fragment-generation-utils-test.js

This addresses two long-standing TODOs in the embiggen function.
The existing behavior does generate valid fragments, but not as
predictably as we'd like, because it doesn't account for the
possibility of multiple boundary characters in a row. This means
some iterations will not actually add a new word to the start/end.
Fixing this now better aligns the existing implementation with the
behavior of the Intl.Segmenter-based implementation, which will be
added as an option in a forthcoming patch.

Fix TODO in embiggen

---

src/fragment-generation-utils.js

Currently, any exception is handled as a timeout. This separates out timeouts from other JS execution errors, to help identify any bugs that may be obscured by this behavior.

Add status code for JS errors

---

package-lock.json
package.json
src/fragment-generation-utils.js
test/fragment-generation-utils-test.js

This updates a few behaviors in fragment generation to be more
consistent with the behavior of Chromium for Android and Desktop.
Specifically, the algorithm now:
* Adds 3 words on the first iteration and 1 word on subsequent
iterations.
* Always adds context to exact text matches that are less than 20
characters long.
A TODO also indicates where a future change will cause context to
be added more often to range-based matches.
These changes should help reduce the number of timeouts we see in
real-world behavior. The step of checking uniqueness can be quite
slow, especially if one or more params are short words that occur
many times in the document. By adding more words sooner, we have
a better chance of succeeding on the first attempt.

Add more context/range words on first iteration

---

src/fragment-generation-utils.js
test/fragment-generation-utils-test.js

This is a follow-up completing a TODO in the last patch. Context
(prefix/suffix) will now be added to generated fragments on the
first iteration when the text for a range-based match is short.
This helps reduce the number of short phrases we search for in
the document, improving our odds of not timing out.

Add context on first iteration for short range-based matches

---

package-lock.json
package.json
src/fragment-generation-utils.js
test/fragment-generation-utils-test.js
test/jp-sentence.html

Currently when we call expandToNearestWordBoundaryPointUsingSegments
on text in Japanese (or any non-space-separated language) we often
include too much text. This is because, if the range already ends on
a word boundary, we jump to the end of the segment where it ends
(i.e., we add another word).
The fix for this is simple; we just early-return whenever the range
points to the beginning/end of a segment, regardless of whether or
not that segment is whitespace.

Fix extraneous characters when expanding JP ranges

---

test/fragment-generation-utils-test.js
test/invisible-text-node.html

When generating the search space for the prefix and suffix, we
attempt to exclude invisible nodes. However, invisible nodes
*between* visible nodes are incorrectly included in the search
space.
This patch adds a test case which is pending (disabled), to
facilitate development of a fix. A future patch will fix the bug
and enable the test.
This issue was first documented at crbug.com/1276014

Adding test case for known issue with invisible text

---

src/fragment-generation-utils.js
src/text-fragment-utils.js

In this patch I'm renaming filterFunction to visibleNodesInRangeFilterFunction and moving the logic to calculate a node's visibility to a separate function. The reason for the refactoring is that we need a different filter function for text-fragment-utils.advanceRangeStartToNonWhitespace. The new filter function will reuse the visibility computation logic and will be added in a future PR.
This PR doesn't change any behaviour.

Refactor filterFunction

---

src/fragment-generation-utils.js
test/fragment-generation-utils-test.js
test/no-text-nodes-in-range.html

This patch covers an edge case of expandToNearestWordBoundaryPointUsingSegments when the start/end of the range can't reach any text nodes without crossing a block boundary.  Added a test cases covering this scenario. More details [here](https://crbug.com/1286003).

Fix crash in expandToNearestWordBoundaryPointUsingSegments

---

src/fragment-generation-utils.js
test/fragment-generation-utils-test.js
test/get-first-text-node-tests.html
test/get-last-text-node-tests.html
test/move-range-edges-to-text-tests.html
test/no-text-after-block-boundary.html

[Bug details](crbug.com/1289262)
Fix: Before trying to generate a matching fragment, if the selected
range doesn't start or end in visible text (e.g: an image), we move
the edges of the range to the first and last visible text inside
the original selection. This removes the unexpected behaviors occurring
when the selection had non text content on its edges.

This patch fixes a link generation bug when selection has non text content on its edges.

---

src/text-fragment-utils.js

Some pages (e.g., Wikipedia) only distinguish links by their text
color (i.e., no underline). When the text color is overridden by
setDefaultTextFragmentsStyle, these links are not distinguishable
from regular text, so users may tap them inadvertently. This patch
updates CSS to ensure an underline is always displayed on links in
this situation.

Show underline on links in highlights

---

src/fragment-generation-utils.js
src/text-fragment-utils.js
test/ambiguous-match.html
test/text-fragment-utils-test.js

Fixing regression I introduced in #114. This regression was preventing processTextFragmentDirective from finding multiple matches for a fragment when its start term occurred multiple times (in the DOM) before its end term. This bug would cause link generation to produce ambiguous fragments in some scenarios.
Added unit test checking the regression scenario.

Fixed regression in processTextFragmentDirective

---

test/data-driven/data-driven-test.js

This patch adds DataDrivenTest, a class used to implement data-driven
tests in the polyfill. This class includes most of the boilerplate
code needed to implement data-driven tests defined in input/ouput
files.
In a future PR, a subclass of DataDrivenTest will be used to implement
Text Fragment data-driven tests for the Test Infrastructure.

Test Infra: Added base class for data-driven tests.

---

package-lock.json
src/text-fragment-utils.js
test/unit/text-fragment-utils-test.js

We've been too strict; according to the spec it is valid if a URL
could identify more than one chunk of text, we should highlight
the first instance.
Ref: https://wicg.github.io/scroll-to-text-fragment/#syntax

Highlight first match when ambiguous

---

src/text-fragment-utils.js

add a `root` element param for `processFragmentDirectives`

feat: add search root element
